#!/usr/bin/with-contenv bash

USER=${USER:-cups}
PASS=${PASS:-cups}

if cat /etc/passwd | grep $USER ; then
  adduser lpadmin $USER
else
  echo "$PASS\n$PASS" | adduser --no-create-home --disabled-password --gecos "" --ingroup lpadmin $USER
  echo "$USER:$PASS" | chpasswd
fi
